spring.datasource.url=jdbc:postgresql://dpg-d8b8n6cm0tmc73db3qhg-a.singapore-postgres.render.com/smartlearn?sslmode=require
spring.datasource.username=smartlearn
spring.datasource.password=smartlearn123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080
server.servlet.context-path=/api

jwt.secret=smartlearn-secret-key-minimum-256-bits-long-change-in-production
jwt.expiry-ms=86400000

ml.service.url=http://localhost:8000
storage.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB